import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import ToastProvider from "@/providers/ToastProvider";
import LoadingDialog from "@/components/LoadingDialog";
import AuthProvider from "@/providers/AuthProvider";
import AppSidebar from "@/components/AppSidebar";
import AppHeader from "@/components/AppHeader";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ReduxProvider>
            <ToastProvider>
              {session?.user ? (
                <div className="flex min-h-screen w-full bg-muted/40">
                  <AppSidebar />
                  <div className="flex flex-1 flex-col space-y-4">
                    <AppHeader />
                    <main className="flex flex-col p-4 sm:py-1 md:gap-8">
                      {children}
                    </main>
                  </div>
                </div>
              ) : (
                <div className="w-full h-screen overflow-hidden">
                  {children}
                </div>
              )}

              <LoadingDialog />
            </ToastProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
